ALTER TABLE goals ALTER COLUMN start_date TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE goals ALTER COLUMN end_date TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE users ALTER COLUMN born_date TYPE TIMESTAMP WITHOUT TIME ZONE;
